### ISSUE TITLE
px.radius = 0 error

### ISSUE THREAD

**Issue by jennv848** [J0vid/Colormesh#7]
When px.radius = 0 in rgb.meassure function, it throws an error.

![mitch-error](https://user-images.githubusercontent.com/69691467/135319123-0f450d67-7a57-4805-b32d-f531d1ce874b.png)

**Comment by J0vid** [comment]
Ok, I think https://github.com/J0vid/Colormesh/commit/f5d373665def3b7617aa6cd7163901ad2ae54218 fixes this issue. Basically, when we normally ask for a sampling circle, we select a neighborhood of pixels around each triangulated point. When px.radius = 1 or 0, we only measure the pixel values which causes an error in the way we calculated the mean returning NaN values for both perimeter and interior points. This happened silently (yikes) unless you tried to linearize the colorspace. 

Let me know if you see any errors with the latest version of the code.
