### ISSUE TITLE
rgb.measure failing when px.radius = 1

### ISSUE THREAD

**Issue by jennv848** [J0vid/Colormesh#8]
I ran the tri.surf function where num.passes = 3 to eliminate the issue identfied when num.passes = 1.
When 3 rounds of triangulation were performed (successfully), I measured the values using rgb.measure. If px.radius = 1, it fails to measures RGB values for the pixels. Both the perimeter and interior points are NaN.

```R
uncalib_RGB = rgb.measure(imagedir = "C:/Users/jennv/OneDrive/Mitch Error/unwarped_images/", image.names =  specimen.factors[,2], delaunay.map = specimen.sampling.template, px.radius = 0, linearize.color.space = FALSE)

uncalib_RGB_px1 = rgb.measure(imagedir = "C:/Users/jennv/OneDrive/Mitch Error/unwarped_images/", image.names =  specimen.factors[,2], delaunay.map = specimen.sampling.template, px.radius = 1, linearize.color.space = FALSE)

uncalib_RGB_px2 = rgb.measure(imagedir = "C:/Users/jennv/OneDrive/Mitch Error/unwarped_images/", image.names =  specimen.factors[,2], delaunay.map = specimen.sampling.template, px.radius = 2, linearize.color.space = FALSE)

```

**Comment by J0vid** [comment]
This is the same issue that caused issue #7 , so I'm going to close it here and address it there. circle.coords(1) and circle.coords(0) produce the same output of (0,0), which will measure the exact pixel value of each triangulated point.
